variant_num: 1
report_dir: './report'
task_1_file: './resources/task1.txt'
task_2_file: './resources/task2.txt'
infinity: 1000000
c_constant_gene: 250
colony_size: 10
q0_ant: 0.75
limit_ant: 100
rho_ant: 0.2